[package]
name = "nxmproxy"
version = "0.2.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = 'abort'
strip = true

[dependencies]
windows = { version = "0.62", features = [
	"Win32_System_Registry",
	"Win32_UI_Shell",
	"Win32_UI_WindowsAndMessaging",
] }
winreg = "0.56"
log = "0.4"

[dev-dependencies]
